dist:
  name: opencodeco-otelcol
  description: Custom OpenTelemetry Collector distribution
  output_path: /output

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.95.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.95.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.95.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.95.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.95.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.95.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.95.0
