receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: 0.0.0.0:14268
  statsd:
    endpoint: 0.0.0.0:8125
    is_monotonic_counter: true

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: 0.0.0.0:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://0.0.0.0:4318
    tls:
      insecure: true

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000

service:
  pipelines:
    traces:
      receivers: [ jaeger ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, otlp, otlphttp ]
    metrics:
      receivers: [ statsd ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, otlp, otlphttp ]
